### ISSUE TITLE
- was called on null

### ISSUE THREAD

**Issue by weboey** [flutterchina/nine_grid_view#1]
flutter 版本2.7.0环境下报错
![image](https://user-images.githubusercontent.com/14002656/87405814-83aafc80-c5f2-11ea-96f6-8a49d07551bd.png)

**Comment by Sky24n** [comment]
报错提供详细点吧

**Comment by weboey** [comment]
当type = weChatGp（dingTalkGp，qqGp）中的值时就会报这个错
![image](https://user-images.githubusercontent.com/14002656/87744286-aa994680-c81d-11ea-9196-7b93f94c65b4.png)

**Comment by Sky24n** [comment]
大哥，头像需要设置宽高的！麻烦你好好看下demo呢
