### ISSUE TITLE
imageList是什么

### ISSUE THREAD

**Issue by WhianGaulin** [flutterchina/nine_grid_view#2]
imageList是List<DragBean>,请问有了List<file>,怎么初始化为List<DragBean>的参数呢

**Comment by WhianGaulin** [comment]
![Uploading QQ截图20201006164740.jpg…]()

**Comment by WhianGaulin** [comment]
![QQ截图20201006164740](https://user-images.githubusercontent.com/43519654/95180244-4c647a00-07f4-11eb-8962-fb5c7bd6f19d.jpg)
![QQ截图20201006164800](https://user-images.githubusercontent.com/43519654/95180250-4d95a700-07f4-11eb-9e93-664d6e1ec6f1.jpg)

**Comment by Sky24n** [comment]
自己先看看demo吧！


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by WhianGaulin** [comment]
您好,Demo看了呢,example里面就是直接给出了imageList和未定义的itemBuilder和initBuilder

**Comment by Sky24n** [comment]
[example](https://github.com/flutterchina/nine_grid_view/tree/master/example/lib)

**Comment by WhianGaulin** [comment]
谢谢,真是打扰了,我太傻了...

**Comment by WhianGaulin** [comment]
您好,example里面的drag_sort_view无法拖拽
![QQ截图20201007200132](https://user-images.githubusercontent.com/43519654/95328308-f79a2f80-08d7-11eb-8c67-979e97a4da6d.jpg)
