### ISSUE TITLE
Example 里 DragSortView 要求传入的是 List<DragBean> 但 imageList 确是List<ImageBean>？

### ISSUE THREAD

**Issue by ljx0520** [flutterchina/nine_grid_view#5]
Example 里 DragSortView 要求传入的是 List < DragBean > 但 imageList 确是List< ImageBean >？

**Comment by Sky24n** [comment]
class ImageBean extends DragBean {

**Comment by ljx0520** [comment]
> class ImageBean extends DragBean {

是哦 大意了 谢谢
